### ISSUE TITLE
Works just fine!

### ISSUE THREAD

**Issue by ImTotallyNotMessi** [ZeCryptic/osu-cat#1]
I saw your reply to someone on Youtube. The script works fine on my computer, im ImTotallyNotMessi in the comments. Only complaint i have is that you cant size the window, or change the background to green and use it with a chromakey.

**Comment by Jacensz** [comment]
The biggest problem was the size of the window since I have small desktop and it appeared almost half my screen when opened

**Comment by JapanPanda** [comment]
Hiya, I actually tweaked the script so that you may resize it as seen in the reference above.
